# Generated by Django 4.1.5 on 2023-01-13 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Plate Area',
                'verbose_name_plural': 'Plate Areas',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=6)),
                ('plate_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plate.platearea')),
            ],
            options={
                'verbose_name': 'Plate',
                'verbose_name_plural': 'Plates',
            },
        ),
    ]
