# Generated by Django 4.1.5 on 2023-01-13 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platearea',
            options={'ordering': ['region'], 'verbose_name': 'Plate Area', 'verbose_name_plural': 'Plate Areas'},
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_plate_number', message='Plate number need be exactly to specifications', regex='^[АВЕКМНОРСТУХ]{1}[/\\d]{3}[АВЕКМНОРСТУХ]{2}$')]),
        ),
        migrations.AlterField(
            model_name='platearea',
            name='region',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
