# Generated by Django 4.1.5 on 2023-01-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_alter_platearea_options_alter_plate_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together={('plate_number', 'plate_area')},
        ),
    ]
